version: '3'
services:
  cloud_connector:
    build: .
  influxdb:
    image: influxdb:1.5.4-alpine
    ports:
    - "8086:8086"
    environment:
     - INFLUXDB_ADMIN_USER=root
     - INFLUXDB_ADMIN_PASSWORD=root