version: '3'
services:
  cloud_connector:
    build: .
  influxdb:
    image: influxdb:1.5-alpine
    ports:
    - "8086:8086"
  chronograf:
    image: chronograf:1.5-alpine
    ports:
    - "8888:8888"
